# Params
                             #[LowerBound, UpperBound]
valid_x_pos_range:             [-20.0, 20.0]
valid_y_pos_range:             [-20.0, 20.0]
valid_z_pos_range:             [0.0, 5.0]
valid_x_vel_range:             [-10.0, 10.0]
valid_y_vel_range:             [-10.0, 10.0]
valid_z_vel_range:             [-10.0, 10.0]
valid_x_acc_range:             [-5.0, 5.0]
valid_y_acc_range:             [-5.0, 5.0]
valid_z_acc_range:             [-5.0, 5.0]

rou:                            0.3

